name: Pode CI - Docs

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
    paths:
    - 'mkdocs.yml'
    - 'mkdocs-overrides/**'
    - 'docs/**'
    - '.github/workflows/ci-docs.yml'
    - 'pode.build.ps1'
    - 'src/Pode.psd1'
  pull_request:
    branches:
    - '*'
    paths:
    - 'mkdocs.yml'
    - 'mkdocs-overrides/**'
    - 'docs/**'
    - '.github/workflows/ci-docs.yml'
    - 'pode.build.ps1'
    - 'src/Pode.psd1'

env:
  INVOKE_BUILD_VERSION: '5.14.4'

jobs:
  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: windows-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Install Invoke-Build
      shell: pwsh
      run: |
        Install-Module -Name InvokeBuild -RequiredVersion $env:INVOKE_BUILD_VERSION -Force

    - name: Build Documentation
      shell: pwsh
      run: |
        Invoke-Build DocsBuild